export const PUZZLE_STRINGS = {
  pageTitle: 'Тренажёр задач',
  pageSub: 'Решай тактические задачи или создавай свои',
  tabs: {
    library: 'Библиотека',
    custom: 'Мои задачи',
    create: 'Создать',
  },
  filters: {
    themes: 'Темы',
    elo: 'Уровень',
    search: 'Поиск',
    searchPlaceholder: 'Поиск по названию или ID',
    reset: 'Сбросить',
    empty: 'По заданным фильтрам ничего не найдено',
  },
  card: {
    sideToMoveWhite: 'Белые ходят',
    sideToMoveBlack: 'Черные ходят',
    elo: 'ELO',
    themes: 'Темы',
    open: 'Решать',
    delete: 'Удалить',
  },
  solver: {
    yourMove: 'Ваш ход',
    waiting: 'Ход соперника…',
    correct: 'Верно!',
    wrong: 'Неверно — попробуйте снова',
    solved: 'Задача решена!',
    failed: 'Решение не найдено',
    next: 'Следующая',
    retry: 'Попробовать заново',
    hint: 'Подсказка',
    backToList: 'К списку',
    progress: (current: number, total: number): string => `Ход ${String(current)} из ${String(total)}`,
    hintsUsed: (n: number): string => `Подсказок: ${String(n)}`,
    opponentLabel: 'Соперник',
    opponentScripted: 'Сценарий',
    opponentAi: 'ИИ (макс.)',
    aiThinking: 'ИИ думает…',
    objectiveEyebrow: 'ЦЕЛЬ',
    objectiveBestMove: 'Найти лучший ход',
    objectiveMate: (n: number): string =>
      `Мат в ${String(n)} ${n === 1 ? 'ход' : n < 5 ? 'хода' : 'ходов'}`,
    objectivePlayLine: 'Сыграть линию',
    budget: (n: number): string =>
      `Бюджет · ${String(n)} ${n === 1 ? 'ход' : n < 5 ? 'хода' : 'ходов'}`,
    budgetMade: (done: number, total: number): string =>
      `${String(done)} / ${String(total)} сделано`,
    aiSolveEyebrow: 'ПУСТЬ РЕШИТ ИИ',
    aiSolveStart: 'Запустить анализ',
    aiSolveLead: 'Движок проанализирует позицию и покажет вариант пошагово на доске.',
    aiSolveThinking: 'Анализирую…',
    aiSolveDepth: (cur: number, max: number): string =>
      `глубина · ${String(cur)} / ${String(max)}`,
    aiSolveReady: 'ИИ готов к визуализации',
    aiSolveBadgeReady: 'готов',
    aiSolveBadgeVis: 'визуал.',
    aiSolveBadgeMissed: 'не справился',
    aiSolveMissedMateTitle: 'ИИ не уложился в бюджет',
    aiSolveMissedMateBody: (found: number, budget: number): string =>
      `Найден мат за ${String(found)} ${found === 1 ? 'ход' : found < 5 ? 'хода' : 'ходов'}, ` +
      `а по условию — за ${String(budget)}. Возможно, мат за ${String(budget)} в этой позиции не форсирован.`,
    aiSolveMissedGenericTitle: 'ИИ не нашёл решение',
    aiSolveMissedGenericBody: 'Лучший вариант движка не соответствует цели задачи.',
    aiSolveShowFirst: 'Показать первый ход',
    aiSolveNext: 'Следующий ход',
    aiSolveRestart: 'Сначала',
    pvHead: (n: number): string => `вариант · ${String(n)} полуходов`,
    historyTitle: 'Ваши ходы',
    historyEmpty: 'Пока нет попыток',
    historyOk: 'верный ход',
    historyBad: 'не подходит',
    bannerSolvedTitle: 'Решено!',
    bannerSolvedBody: (n: number): string =>
      `За ${String(n)} ${n === 1 ? 'ход' : n < 5 ? 'хода' : 'ходов'}.`,
    bannerFailedTitle: 'Цель не достигнута',
    bannerFailedBody: 'Бюджет исчерпан. Попробуйте ещё раз или попросите подсказку.',
    continueFromPosition: 'Продолжить с этой позиции',
  },
  editor: {
    objective: {
      label: 'Цель задачи',
      movesLabel: 'Бюджет ходов',
      kindScripted: 'Сценарий',
      kindBestMove: 'Лучший ход',
      kindMate: 'Мат за N',
      hintScripted:
        'Игрок должен сыграть в точности по сохранённой линии решения. ' +
        'Ошибочный ход — задача провалена.',
      hintBestMove:
        'Игроку разрешён один ход. Засчитывается только первый ход из решения ' +
        '(например, bm из EPD).',
      hintMate: (n: number): string =>
        `Игрок может сыграть любые легальные ходы. Цель — поставить мат не позже чем за ${String(n)} ${n === 1 ? 'ход' : n < 5 ? 'хода' : 'ходов'}. ` +
        `Если за бюджет мата нет — задача провалена.`,
    },
    title: 'Создание задачи',
    sub: 'Введите FEN, выберите сторону и запишите решение',
    editTitle: 'Редактирование задачи',
    editSub: 'Изменяйте позицию, темы и решения',
    update: 'Сохранить изменения',
    updated: 'Изменения сохранены',
    edit: 'Редактировать',
    fenLabel: 'Стартовая позиция (FEN)',
    fenPlaceholder: 'Скопируйте FEN из вашей партии',
    fenInvalid: 'Неверный FEN',
    sideLabel: 'Чей ход',
    titleLabel: 'Название',
    titlePlaceholder: 'Например: «Жертва ферзя»',
    themesLabel: 'Темы',
    eloLabel: 'Сложность (ELO)',
    descriptionLabel: 'Описание (опционально)',
    recordLabel: 'Делайте ходы на доске — они запишутся в активную линию',
    linesLabel: 'Линии решения',
    lineName: (n: number): string => `Линия ${String(n)}`,
    addLine: 'Альтернативная линия',
    deleteLine: 'Удалить линию',
    solutionEmpty: 'Пока нет ходов',
    clearMoves: 'Очистить активную',
    save: 'Сохранить задачу',
    saved: 'Задача сохранена',
    requiredFields: 'Заполните FEN и хотя бы один ход решения',
  },
  empty: {
    custom: 'У вас пока нет своих задач. Создайте первую в соседней вкладке.',
  },
  fenBuilder: {
    title: 'Конструктор позиции',
    sub: 'Расставляйте, перетаскивайте и удаляйте фигуры, чтобы получить нужный FEN',
    initial: 'Начальная позиция',
    clear: 'Очистить доску',
    flip: 'Перевернуть доску',
    paletteWhite: 'Белые',
    paletteBlack: 'Чёрные',
    toolHint: 'Выберите фигуру и кликайте по клеткам, либо перетаскивайте. ✕ — удалить.',
    sideLabel: 'Чей ход',
    sideWhite: 'Белые',
    sideBlack: 'Чёрные',
    castlingLabel: 'Права на рокировку',
    fenLabel: 'FEN строка',
    invalid: 'Неверный FEN',
    copy: 'Скопировать',
    copied: 'Скопировано',
    useInEditor: 'Использовать в редакторе',
    back: 'К редактору',
    openLink: 'Открыть конструктор позиции',
  },
} as const;
